export const CORRECT_ANSWER_DELAY_MS = 1200;
export const INCORRECT_ANSWER_DELAY_MS = 1700;
export const GAME_OVER_SUMMARY_DELAY_MS = 1500;
export const SPLASH_SCREEN_MIN_DURATION_MS = 2000;
export const SOUND_CLEANUP_DELAY_MS = 3000;
export const STORE_REVIEW_PULSE_DURATION_MS = 2000;
